# Application identification
spring.application.name=Gateway

# Config Client configuration
spring.cloud.config.enabled=true
spring.cloud.config.uri=http://config-server:8888
spring.config.import=optional:configserver:http://config-server:8888

# Local-only properties
server.port=8083

# Enable dynamic route discovery from Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka registration (DO NOT use localhost in Docker)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Keycloak configuration (INSIDE Docker ? use container name + internal port)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/JobBoardKeyClock
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/JobBoardKeyClock/protocol/openid-connect/certs
