version: '3.8'

services:
  eureka-server:
    build: ../Eureka
    ports: ["8761:8761"]
    networks:
      - bookstore-net

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container  # Ajout explicite du nom du conteneur
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookstore
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bookstore-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10

  bookstore-app:
    image: sarrabennour/booki-payment:1.0.0
    hostname: bookstore-app  # Force le hostname DNS
    container_name: bookstore-app  # Nom cohérent
    depends_on:
      mysql-container:
        condition: service_healthy
      eureka-server:
        condition: service_started
    ports:
      - "8085:8085"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=bookstore-app  # Surcharge explicite
      - SPRING_APPLICATION_NAME=bookstore-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/bookstore?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      bookstore-net:
        aliases:
          - bookstore-app.localhost

volumes:
  mysql-data:

networks:
  bookstore-net:
    driver: bridge