# Nom de l'application dans Eureka
spring.application.name=paiement-service

# Port d'écoute
server.port=8085

# Secret JWT (à adapter si nécessaire)
app.jwtSecret=yourSecretKeyHere12345678901234567890123456789012

# Configuration Eureka (utiliser eureka-server en Docker)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# Désactiver le config server si non utilisé
spring.cloud.config.enabled=false

# Clé Stripe (test)
stripe.secret.key=sk_test_51RezfWI0cj2k0JXHxXLPQasIY8qlRdU1d15nvkumU4oX8M7XOfDQaKdinmyhGuZOSN2Gu40suRuFlMCbb7RKmIMV00pFaYAvHQ
stripe.public.key=pk_test_51RezfWI0cj2k0JXHBN4OF9MrJXawRK1AVMZIBEw7CZR6ujngF2DS9Q0aNU5AXYLEBqn84kwhUcgywDxmEugTgYsA00TumuuTtq

# Configuration email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yassinosb7@gmail.com
spring.mail.password=sbgo jgya ejct iciq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Pour ignorer le Config Server manquant (sécurité)
spring.config.import=optional:configserver:http://eureka-server:8888
