# Nom unique du service (important pour Eureka)
spring.application.name=Booki

# Port d'écoute dans le conteneur (doit être unique)
server.port=8082

# Configuration du client Eureka (ne jamais utiliser localhost en Docker)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# Configuration du client Config Server
spring.cloud.config.enabled=true
spring.cloud.config.uri=http://config-server:8888
spring.config.import=optional:configserver:http://config-server:8888

# Clé secrète JWT
app.jwtSecret=yourSecretKeyHere12345678901234567890123456789012
