# Application
server.port=8083
spring.application.name=Gateway

# Eureka (Docker ? use container name, not localhost)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Keycloak (Docker ? container name is 'keycloak', default internal port is 8080)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/JobBoardKeyClock

# Logging
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.reactor.netty.http.client=DEBUG
