# Give your config server a name
spring.application.name=configserver

# Port it listens on
server.port=8888

# Register to Eureka (DO NOT use localhost in Docker)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.server.wait-time-in-ms-when-sync-empty=5

# Use native config (files in folder)
spring.profiles.active=native

# ? IMPORTANT: use absolute path inside Docker image (NOT classpath!)
spring.cloud.config.server.native.searchLocations=file:/config
